### ISSUE TITLE
Not .netcore friendly (yet)

### ISSUE THREAD

**Issue by nathancarmona** [thyn/haproxy-api#1]
Before I start drudging through a rewrite to make this play nice with .Net Core with an intention of using in AWS Lambda, I just wanted to make sure this isn't something that was already underway. 

Did you have any intention or have you potentially started doing this?

**Comment by thyn** [comment]
No .Net Core not supported yet. If you like you can make pull request. It is a small library to have something to start from. Changes are welcome.

**Comment by nathancarmona** [comment]
Cool deal, will do!

**Comment by thyn** [comment]
I've changed some code. Please take  code. I think it is possible to remove dependency on csv library package. Will it help you?

**Comment by nathancarmona** [comment]
cool, ill take a look

**Comment by nathancarmona** [comment]
Had to switch to a different CSV parsing package (CSV Parser) and make a few things .Net friendly. Just testing now.

**Comment by thyn** [comment]
cool, thank you

**Comment by thyn** [comment]
Hi, how are you? Could you please give non friendly version I will fix it)
